# Generated by Django 5.2.5 on 2025-08-30 20:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discord_guild_id', models.CharField(help_text='Discord Guild ID (Server ID)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Discord server name', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Should daily bot be active in this server?')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
    ]
